# Generated by Django 5.0.7 on 2024-11-02 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagementapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('isdelete', models.IntegerField()),
                ('isactive', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='logindata',
            name='role',
            field=models.CharField(default='Employee', max_length=255),
        ),
        migrations.AlterField(
            model_name='logindata',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logindata',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='logindata',
            name='user_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='EmployeeManagementapp.employeeregister'),
        ),
    ]
