# Generated by Django 5.0.7 on 2024-11-03 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagementapp', '0002_employeeregister_logindata_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindata',
            name='user_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagementapp.employeeregister'),
        ),
    ]
